name: Install dependencies

description: 'Install dependencies'
runs:
  using: "composite"

  steps:
    - name: Checkout NVDA repository
      uses: actions/checkout@v4
      with:
        repository: nvaccess/nvda.git
        ref: master
        path: ${{ github.workspace }}/Tools/NVDA
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: x86
    - name: Cache dependencies
      id: cacheDependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/Tools/NVDA/.venv
        key: ${{ runner.os }}-${{ hashFiles('Tools/NVDA/requirements.txt') }}
    - name: Create Python virtual environment
      shell: cmd
      run: |
        python -m venv ${{ github.workspace }}\Tools\NVDA\.venv
        call ${{ github.workspace }}\Tools\NVDA\.venv\Scripts\activate.bat
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/Tools/NVDA/requirements.txt
