name: Install dependencies

description: 'Install dependencies'
inputs:
  use-cache:
    description: 'Indicates if cache action should be used: true or false'
    default: 'true'
runs:
  using: "composite"

  steps:
    - name: Checkout NVDA repository
      uses: actions/checkout@v4
      with:
        repository: nvaccess/nvda.git
        ref: master
        path: ${{ github.workspace }}/Tools/NVDA
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: x86
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ github.workspace }}/Tools/NVDA/requirements.txt
