name: Install dependencies for addon

description: 'Install dependencies for addon'
runs:
  using: "composite"

  steps:
    - name: Checkout CrowdinRegistration repository
      uses: actions/checkout@v5
      with:
        repository: nvdaaddons/CrowdinRegistration
        ref: main
        path: ${{ github.workspace }}/Tools/CrowdinRegistration
        sparse-checkout: utils
    - name: Checkout miscDeps
      uses: actions/checkout@v5
      with:
        repository: nvaccess/nvda-misc-deps
        path: ${{ github.workspace }}/Tools/CrowdinRegistration/miscDeps
        sparse-checkout: tools
    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Python Dependencies
      shell: cmd
      run: |
        python -m pip install --upgrade pip
        pip install crowdin-api-client
        pip install lxml requests 
        pip install Markdown
        pip install mdx_truly_sane_lists
        pip install markdown-link-attr-modifier
        pip install mdx-gh-links
        pip install nh3
