name: Automatically update NVDA.po

on:
  push:
    branches:
      - "CheckPot"
  workflow_dispatch:

jobs:
  Automatically-Update-NVDA-po:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache gettext
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/Crowdin/Temp/gettext.zip
          key: gettext-${{ hashFiles('Crowdin/Temp/gettext.zip') }}
      - name: Download gettext
        uses: carlosperate/download-file-action@v2
        with:
          file-url: https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.24-v1.17/gettext0.24-iconv1.17-static-32.zip
          file-name: gettext.zip
          location: ${{ github.workspace }}/Crowdin/Temp
          sha256: c14d844f4950e14189fe47795700172f019ec2f5430bfa068a7a909ff784f45c
      - name: Install dependencies
        uses: ./.github/InstallDependencies
        with:
          submodules: true
      - name: Configure environment
        id: Set_Environment_Variables
        shell: pwsh
        run: |
          cd "${{ github.workspace }}/Tools/NVDA"
          $commit = (git rev-parse --short HEAD).Trim()
          echo "commit=$commit" >> $env:GITHUB_OUTPUT
          cd "${{ github.workspace }}"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          $versionFile = "${{ github.workspace }}/Tools/NVDA/source/buildVersion.py"
          $versionYear = (Select-String -Path $versionFile -Pattern 'version_year\s*=\s*(\d+)').Matches.Groups[1].Value
          $versionMajor = (Select-String -Path $versionFile -Pattern 'version_major\s*=\s*(\d+)').Matches.Groups[1].Value
          $branchName = "$versionYear.$versionMajor"
          echo "Branch=$branchName" >> $env:GITHUB_OUTPUT
          git ls-remote --exit-code --heads origin "$branchName"
          if ($LASTEXITCODE -eq 0) {
            Write-Output "Branch $branchName exists. Checking out..."
            git checkout -b $branchName remotes/origin/$branchName
          } else {
            Write-Output "Branch $branchName does not exist. Creating from Uploads..."
            git checkout -b $branchName remotes/origin/CheckPot
            # git checkout -b $branchName remotes/origin/Uploads
          }
          &"${{ github.workspace }}\Tools\7Zip\7z.exe" e "${{ github.workspace }}\Crowdin\Temp\gettext.zip" "bin\msgmerge.exe" -aoa -o"${{ github.workspace }}\Tools"
      - name: CheckPot
        shell: cmd
        run: |
          cd /d ${{ github.workspace }}\Tools\NVDA
          scons checkPot --all-cores
      - name: Update NVDA.po
        shell: pwsh
        run: |
          &"${{ github.workspace }}\Tools\msgmerge.exe" --update  --backup=none --previous "${{ github.workspace }}\Translation\LC_MESSAGES\nvda.po" "${{ github.workspace }}\Tools\NVDA\output\nvda.pot"
          git add "${{ github.workspace }}\Translation\LC_MESSAGES\nvda.po"
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新界面可翻译字符串（alpha-${{ steps.Set_Environment_Variables.outputs.commit }}）"
              git push origin  ${{ steps.Set_Environment_Variables.outputs.Branch }}
          } else {
              Write-Host "No changes to commit, skipping commit and push."
          }
      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: NVDA.pot
          path: ${{ github.workspace }}/Tools/NVDA/output/*
