name: Pull Request to NVDA

on:
  push:
    branches:
      - "Uploads"
    paths:
      - 'Translation/miscDeps/*'
  workflow_dispatch:

jobs:

  Pull-Request-To-NVDA:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
      - name: Checkout NVDA repository
        uses: actions/checkout@v4
        with:
          repository: wmhn1872265132/NVDA.git
#          repository: nvaccess/nvda.git
          token: ${{ secrets.PULLREQUESTTONVDA }}
          fetch-depth: 0
          ref: beta
          path: ${{ github.workspace }}/Tools/NVDA
      - name: Configure environment
        shell: cmd
        env:
          miscDepsPath: ${{ github.workspace }}/Translation/miscDeps
          ZHCNPath: ${{ github.workspace }}/Tools/NVDA/source/locale/zh_CN
        run: |
          CD /D %ZHCNPath%
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git switch -c PullRequestToNVDA origin/beta
          IF EXIST "%ZHCNPath%\characterDescriptions.dic" (del /f /q "%ZHCNPath%\characterDescriptions.dic")
          IF EXIST "%ZHCNPath%\gestures.ini" (del /f /q "%ZHCNPath%\gestures.ini")
          IF EXIST "%ZHCNPath%\symbols.dic" (del /f /q "%ZHCNPath%\symbols.dic")
          MKLINK /H "%ZHCNPath%\characterDescriptions.dic" "%miscDepsPath%\characterDescriptions.dic"
          MKLINK /H "%ZHCNPath%\gestures.ini" "%miscDepsPath%\gestures.ini"
          MKLINK /H "%ZHCNPath%\symbols.dic" "%miscDepsPath%\symbols.dic"
          git add "%ZHCNPath%"
          git commit -m "更新符号翻译"
          git push --force origin PullRequestToNVDA:PullRequestToNVDA
