name: Pull Request to NVDA

on:
  push:
    branches:
      - "Uploads"
      - "miscDepsTest"
    paths:
      - 'Translation/miscDeps/*'
  workflow_dispatch:

jobs:

  Pull-Request-To-NVDA:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
      - name: Checkout NVDA repository
        uses: actions/checkout@v4
        with:
          repository: nvaccess/nvda.git
          token: ${{ secrets.PULLREQUESTTONVDA }}
          fetch-depth: 0
          ref: beta
          path: ${{ github.workspace }}/Tools/NVDA
      - name: Processing Files
        shell: cmd
        env:
          miscDepsPath: ${{ github.workspace }}\Translation\miscDeps
          ZHCNPath: ${{ github.workspace }}\Tools\NVDA\source\locale\zh_CN
        run: |
          CD /D %ZHCNPath%
          git remote add NVDACN https://github.com/nvdacn/nvda.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git switch -c PullRequestToNVDA origin/beta
          for %%F in (
            characterDescriptions.dic
            gestures.ini
            symbols.dic
          ) do (
            if exist "%ZHCNPath%\%%F" (del /f /q "%ZHCNPath%\%%F")
            XCopy /I /q /v /h /r /y "%miscDepsPath%\%%F" "%ZHCNPath%"
            git add "%ZHCNPath%\%%F"
          )
          git commit -m "更新符号翻译"
          git push --force NVDACN PullRequestToNVDA:PullRequestToNVDA

  Create_PR:
    runs-on: ubuntu-latest
    needs: Pull-Request-To-NVDA
    steps:
      - uses: actions/checkout@v4
      - name: Check for existing PR
        id: check_pr
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PULLREQUESTTONVDA }}
          script: |
            const result = await github.rest.pulls.list({
              owner: "wmhn1872265132",
              repo: "nvda",
              state: "open",
              head: "nvdacn:PullRequestToNVDA",
              base: "beta"
            });
            if (result.data.length > 0) {
              core.setOutput("pr_exists", "true");
              console.log("Existing PR found:", result.data[0].html_url);
            } else {
              core.setOutput("pr_exists", "false");
              console.log("No existing PR found");
            }
      - name: Render template
        if: steps.check_pr.outputs.pr_exists != 'true'
        id: template
        uses: chuhlomin/render-template@v1
        with:
          template: ${{ github.workspace }}/.github/pull-request-template.md
      - name: Create PR via API
        if: steps.check_pr.outputs.pr_exists != 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PULLREQUESTTONVDA }}
          script: |
            await github.rest.pulls.create({
              owner: "wmhn1872265132",
              repo: "NVDA",
              title: "Automated PR from GitHub Actions",
              head: "nvdacn:PullRequestToNVDA",
              base: "beta",
              body: `${{ steps.template.outputs.result }}`
            });
