name: Pull Request to NVDA

on:
  push:
    branches:
      - "Uploads"
      - "miscDepsTest"
#    paths:
#      - 'Translation/miscDeps/*'
  workflow_dispatch:

jobs:

  Pull-Request-To-NVDA:
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v4
      - name: Checkout NVDA repository
        uses: actions/checkout@v4
        with:
          repository: nvaccess/nvda.git
          token: ${{ secrets.PULLREQUESTTONVDA }}
          fetch-depth: 0
          ref: beta
          path: ${{ github.workspace }}/Tools/NVDA
      - name: Processing Files
        shell: cmd
        env:
          miscDepsPath: ${{ github.workspace }}\Translation\miscDeps
          ZHCNPath: ${{ github.workspace }}\Tools\NVDA\source\locale\zh_CN
        run: |
          CD /D %ZHCNPath%
          git remote add NVDACN https://github.com/wmhn1872265132/NVDA.git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git switch -c PullRequestToNVDA origin/beta
          for %%F in (
            characterDescriptions.dic
            gestures.ini
            symbols.dic
          ) do (
            if exist "%ZHCNPath%\%%F" (del /f /q "%ZHCNPath%\%%F")
            XCopy /I /q /v /h /r /y "%miscDepsPath%\%%F" "%ZHCNPath%"
            git add "%ZHCNPath%\%%F"
          )
          git commit -m "更新符号翻译"
          git push --force NVDACN PullRequestToNVDA:PullRequestToNVDA
      - name: Create PR via API
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PULLREQUESTTONVDA }}
          script: |
            await github.rest.pulls.create({
              owner: "wmhn1872265132",
              repo: "NVDA",
              title: "Automated PR from GitHub Actions",
              head: "wmhn1872265132:PullRequestToNVDA",
              base: "beta",
              body: "Test"
            });
