name: Update Addons Translations from Crowdin

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      Addon_ID:
        description: 'Add-on ID, multiple separated by spaces(optional)'
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  Determine-Branch:
    name: Determine branch
    if: ${{ vars.Run_Addon_Translations_Workflow }}
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.Determine_branch.outputs.Branch }}
    steps:
      - name: Checkout NVDA buildVersion.py
        uses: actions/checkout@v5
        with:
          repository: nvaccess/nvda
          ref: master
          path: ${{ github.workspace }}/NVDA
          sparse-checkout: source/buildVersion.py
      - name: Determine branch name
        id: Determine_branch
        run: |
          versionFile="${{ github.workspace }}/NVDA/source/buildVersion.py"
          versionYear=$(grep -oP 'version_year\s*=\s*\K\d+' "$versionFile")
          versionMajor=$(grep -oP 'version_major\s*=\s*\K\d+' "$versionFile")
          branchName="$versionYear.$versionMajor"
          echo "Branch=$branchName" >> $GITHUB_OUTPUT
      - name: Check branch exists
        id: check_branch
        uses: actions/github-script@v8
        with:
          script: |
            try {
              await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/${{ steps.Determine_branch.outputs.Branch }}'
              });
              console.log(`Branch ${{ steps.Determine_branch.outputs.Branch }} exists`);
              return true;
            } catch (error) {
              if (error.status === 404) {
                console.log(`Branch ${{ steps.Determine_branch.outputs.Branch }} does not exist`);
                return false;
              }
              throw error;
            }
          result-encoding: string
      - name: Manually trigger CheckPot workflow
        if: steps.check_branch.outputs.result != 'true'
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'CheckPot.yaml',
              ref: 'Uploads'
            });

  Update-Addon-Translations:
    name: Update addon translations from Crowdin
    needs: Determine-Branch
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ needs.Determine-Branch.outputs.branch }}
      - name: Install dependencies
        uses: ./.github/workflows/InstallDependenciesForAddon
      - name: Configure environment
        shell: pwsh
        run: |
          $CrowdinToken = "${{ secrets.NVDA_CROWDIN }}"
          $CrowdinToken | Out-File -FilePath ~/.nvda_crowdin -Encoding ascii
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - name: List directories
        if: ${{ !github.event.inputs.Addon_ID }}
        id: dir_list
        shell: pwsh
        run: |
          $dirs = Get-ChildItem -Path "${{ github.workspace }}\Translation\Addons" -Directory | Select-Object -ExpandProperty Name
          $dirsString = $dirs -join " "
          Write-Output "dirs=$dirsString" >> $env:GITHUB_OUTPUT
      - name: Fetch translations
        shell: pwsh
        env:
          AddonID: ${{ github.event.inputs.Addon_ID || steps.dir_list.outputs.dirs }}
        run: |
          $ErrorActionPreference = 'Stop'
          $L10nUtil = "${{ github.workspace }}/L10nUtilTools.bat"
          $addonIds = $env:AddonID -split ' '
          foreach ($addonId in $addonIds) {
              Write-Output "Processing addon: $addonId"
              & cmd /c "$L10nUtil DAP $addonId"
              & cmd /c "$L10nUtil DAX $addonId"
              git add "Translation/Addons/$addonId"
          }
      - name: Commit & Push
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新插件翻译（从 Crowdin）"
              git pull --rebase
              git push
          } else {
              Write-Host "No changes to commit, skipping commit and push."
          }
