name: Update NVDA Translations from Crowdin

on:
  workflow_dispatch:

jobs:
  Update-Translations:
    name: Update translations
    if: github.repository == 'nvdacn/zh_CN_Translation'
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: Uploads
      - name: Install dependencies
        uses: ./.github/workflows/InstallDependencies
      - name: Configure environment
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $CrowdinToken = "${{ secrets.NVDA_CROWDIN }}"
          $CrowdinToken | Out-File -FilePath ~/.nvda_crowdin -Encoding ascii
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        if: success()
      - name: Update Translations
        run: |
          ${{ github.workspace }}/L10nUtilTools.bat DLA
          git add --update Translation
      - name: Commit & Push
        id: check-changes
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新翻译（从 Crowdin）"
              git pull --rebase
              git push
              echo "has_changes=true" >> $env:GITHUB_OUTPUT
          } else {
              Write-Host "No changes to commit, skipping commit and push."
              echo "has_changes=false" >> $env:GITHUB_OUTPUT
          }
      - name: Manually trigger build workflow
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yaml',
              ref: 'Uploads'
            });
