name: Upload Translation

on:
  push:
    branches:
      - "Uploads"
      - "UploadsTest"
  workflow_dispatch:

jobs:

  Process-Translation:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout NVDA repository
        uses: actions/checkout@v4
        with:
          repository: nvaccess/nvda.git
          fetch-depth: 1
#          ref: master
          ref: l10nUtil
          path: ${{ github.workspace }}/Tools/NVDA
          sparse-checkout: |
            source/.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}\Tools\NVDA\requirements.txt
      - name: Create token and branch
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $CrowdinToken = "${{ secrets.NVDA_CROWDIN }}"
          $CrowdinToken | Out-File -FilePath ~/.nvda_crowdin -Encoding ascii
        if: success()
      - name: Process Docs Translation
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $GIT_BEFORE = "${{ github.event.before }}"
          $IsBeforeValid = $false
          $L10nUtil = "${{ github.workspace }}\L10nUtilTools.bat"
          $ProcessedFileList = "Translation/LC_MESSAGES/*.po", "Translation/user_docs/*.xliff"
          git branch main remotes/origin/main
          if (-not [string]::IsNullOrEmpty($GIT_BEFORE)) {
              if (git cat-file -e $GIT_BEFORE 2>$null) {
                  $IsBeforeValid = $true
              }
          }
          if ($IsBeforeValid) {
              $diffRange = "$GIT_BEFORE..HEAD"
          } else {
              Write-Host "Fallback: Fetching latest main branch"
              $MainHead = (git rev-parse "main")
              $diffRange = "$MainHead..HEAD"
          }
          foreach ($ProcessedFileName in $ProcessedFileList) {
              $changedFiles = git diff --name-only $diffRange -- $ProcessedFileName
              foreach ($file in $changedFiles) {
                  Write-Host "$file has changed"
                  $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file)
                  if ($baseName -ieq "nvda") {
                      $FilePath = "Translation/LC_MESSAGES/$baseName.po"
                  } else {
                      $FilePath = "Translation/user_docs/$baseName.xliff"
                  }
                  if (Test-Path $FilePath) {
                      Write-Host "Download"
                      $L10nUtil UP_$baseName
                  } else {
                      Write-Host "Latest"
                  }
              }
          }
        if: success()
