name: Upload NVDA translations to Crowdin

on:
  push:
    branches:
      - "Uploads"
    paths:
      - 'Translation/LC_MESSAGES/*.po'
      - 'Translation/user_docs/*.xliff'

jobs:
  Process-Translations:
    name: Upload translation to Crowdin
    if: ${{ vars.Run_NVDA_Translations_Workflow }}
    runs-on: windows-latest
    steps:
      - name: Checkout ${{ github.repository }} repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/workflows/InstallDependencies
      - name: Configure environment
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $CrowdinToken = "${{ secrets.NVDA_CROWDIN }}"
          $CrowdinToken | Out-File -FilePath ~/.nvda_crowdin -Encoding ascii
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
        if: success()
      - name: Process Translations
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $GIT_BEFORE = "${{ github.event.before }}"
          $IsBeforeValid = $false
          $L10nUtil = "${{ github.workspace }}/L10nUtilTools.bat"
          $ProcessedFileList = "Translation/LC_MESSAGES/*.po", "Translation/user_docs/*.xliff"
          git branch main remotes/origin/main
          if (-not [string]::IsNullOrEmpty($GIT_BEFORE)) {
              git rev-parse --verify -q "$GIT_BEFORE^{commit}" > $null 2>&1
              if ($LASTEXITCODE -eq 0) {
                  $IsBeforeValid = $true
              }
          }
          if ($IsBeforeValid) {
              Write-Host "Comparing changes in range: $GIT_BEFORE"
              $diffRange = "$GIT_BEFORE..HEAD"
          } else {
              Write-Host "Fallback: Fetching latest main branch"
              $MainHead = (git rev-parse "main")
              $diffRange = "$MainHead..HEAD"
          }
          foreach ($ProcessedFileName in $ProcessedFileList) {
              $changedFiles = git diff --name-only $diffRange -- $ProcessedFileName
              foreach ($file in $changedFiles) {
                  Write-Host "$file has changed"
                  $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file)
                  if ($baseName -ieq "nvda") {
                      $FilePath = "Translation/LC_MESSAGES/$baseName.po"
                  } else {
                      $FilePath = "Translation/user_docs/$baseName.xliff"
                  }
                  if (Test-Path $FilePath) {
                      Write-Host "Uploading $file to Crowdin..."
                      & cmd /c "$L10nUtil UP_$baseName"
                      Start-Sleep -Seconds 5
                      Write-Host "Downloading updated $file from Crowdin..."
                      & cmd /c "$L10nUtil DL_$baseName"
                      git add "$file"
                      Write-Host "Staged changes for $file"
                  } else {
                      Write-Host "File $FilePath not found, skipping processing."
                  }
              }
          }
        if: success()
      - name: Commit & Push
        id: check-changes
        shell: pwsh
        run: |
          git diff --cached --quiet
          if ($LASTEXITCODE -ne 0) {
              git commit -m "更新已上传的翻译文件（从 Crowdin）"
              git pull --rebase
              git push origin ${{ github.ref_name }}
              echo "has_changes=true" >> $env:GITHUB_OUTPUT
          } else {
              Write-Host "No changes to commit, skipping commit and push."
              echo "has_changes=false" >> $env:GITHUB_OUTPUT
          }
      - name: Manually trigger build workflow
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yaml',
              ref: 'Uploads'
            });
